#pragma once
#include <vector>
#include <cstdint>

// AUTOMATICALLY GENERATED BY GRADLE
// Generated at: 1768974669098

static const int EXPECTED_DEX_COUNT = 2;
static const uint32_t EXPECTED_DEX_CRCS[] = { 0xDCDFAB2D, 0x7CFF642D };